name: Generate translations
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.ACCESS_TOKEN }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            # Install dependencies
            - name: Install NPM Packages
              run: npm install
              env:
                  NODE_AUTH_TOKEN: $\{{ secrets.PAT }}

            # Generate translations with astro-i18next package
            - name: Run astro-i18next
              run: npx astro-i18next generate
              env:
                  NODE_AUTH_TOKEN: $\{{ secrets.PAT }}

            # Add files that were created during a run
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update translations
