name: Generate translations
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{secrets.BOT_ACCESS_TOKEN}}

            - name: Setup Node.js environment
              uses: actions/setup-node@v2

            # Install dependencies
            - run: yarn install

            # Generate translations with astro-i18next package
            - run: npx astro-i18next generate

            # Add files that were created during a run
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update translations

                  commit_user_name: cbasje-bot
                  commit_user_email: github-bot@benjami.in
                  commit_author: Github Actions Bot <github-bot@benjami.in>
